version: '2'
services:

  backend:
    image: localhost:5000/vault_dragon-backend
    depends_on:
      - db
  
  proxy:
    depends_on:
      - backend
    volumes:
      - ./configuration/deployment/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./configuration/deployment/config
    ports:
      - 80:80
