version: '2'
services:

  frontend:
    image: localhost:5000/pets4ever-frontend

  backend:
    image: localhost:5000/pets4ever-backend
    depends_on:
      - db
  
  proxy:
    depends_on:
      - frontend
      - backend
    volumes:
      - ./configuration/deployment/nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./configuration/deployment/config
    ports:
      - 80:80
